<a href="https://colab.research.google.com/github/Devi128/DBMS/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Perform arithmetic operations on NumPy arrays.

In [7]:
a=np.array([1,3,4,5])
b=np.array([2,6,8,7])
print("addition:",a+b)
print("subtraction:",a-b)
print("multiplication:",a*b)
print("modulo:",a%b)
print("floor division:",a//b)
print("Exponentiation:",a**2)

addition: [ 3  9 12 12]
subtraction: [-1 -3 -4 -2]
multiplication: [ 2 18 32 35]
modulo: [1 3 4 5]
floor division: [0 0 0 0]
Exponentiation: [ 1  9 16 25]


Write a script to compute the mean and standard deviation of a NumPy array.

In [8]:
data = np.array([11, 30, 4, 3, 52])
mean_value = np.mean(data)
std_dev = np.std(data)
print("Data Array:", data)
print("Mean:", mean_value)
print("Standard Deviation:", std_dev)


Data Array: [10 20 30 40 50]
Mean: 30.0
Standard Deviation: 14.142135623730951


Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [13]:
a=np.arange(10,50,5)
print(a)

[10 15 20 25 30 35 40 45]


Reshape the array into a 2x4 matrix.

In [14]:
arr=np.array([10,15,20,25,30,35,40,45])
reshaped_array = arr.reshape(2, 4)
print("Original Array:", arr)
print("Reshaped 2x4 Matrix:")
print(reshaped_array)


Original Array: [10 15 20 25 30 35 40 45]
Reshaped 2x4 Matrix:
[[10 15 20 25]
 [30 35 40 45]]


Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
•
Extract the sub-matrix containing the last two rows and first two columns.
•
Replace all elements greater than 4 with 0.

In [21]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
submatrix=arr[1:, :2]
arr[arr>4]=0
print(arr)
print(submatrix)

[[1 2 3]
 [4 0 0]
 [0 0 0]]
[[4 0]
 [0 0]]


Create two 1D arrays:
•
a = np.array([1, 2, 3])
•
b = np.array([4, 5, 6])
•
Perform element-wise addition, multiplication, and division.

In [22]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("addition:",a+b)
print("multiplication:",a*b)
print("division:",a/b)

addition: [5 7 9]
multiplication: [ 4 10 18]
division: [0.25 0.4  0.5 ]


Create a random NumPy array of size (4, 4). Compute:
•
Mean of each column.
•
Maximum value of the entire array.
•
Sum of all elements

In [25]:
arr=np.random.rand(4,4)
mean=np.mean(arr,axis=0)
max_value=np.max(arr)
sum=np.sum(arr)
print(arr)
print("mean of each column:",mean)
print("Maximum value of the entire array:",max_value)
print("Sum of all elements:",sum)

[[0.04423149 0.12707596 0.44399077 0.46066536]
 [0.27942571 0.22606665 0.92313374 0.95613603]
 [0.48845934 0.59160933 0.56933083 0.80138393]
 [0.64363148 0.93749772 0.36715308 0.82064467]]
mean of each column: [0.363937   0.47056241 0.5759021  0.7597075 ]
Maximum value of the entire array: 0.9561360277822751
Sum of all elements: 8.680436062482107


Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply the result by 2.

In [26]:
 arr = np.array([1, 2, 3, 4])
 add=arr+10
 result=add*2
 print("result:",result)

result: [22 24 26 28]


Perform advanced slicing and indexing on a 3D array. Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from 1 to 100. Perform the following:
•
Extract the second "layer" (i.e., the second 2D array) in the first dimension.
•
Extract the first two rows and the last three columns from each "layer."
•
Replace all elements divisible by 3 with -1.

In [27]:
arr = np.random.randint(1, 101, size=(3, 4, 5))
second_layer = arr[1]
subset = arr[:, :2, -3:]
arr[arr % 3 == 0] = -1
print("Original 3D Array:")
print(arr)
print("Second 2D array in the first dimension",second_layer)
print("First two rows, last three columns from each layer",subset)


Original 3D Array:
[[[ 43  83  -1  -1  20]
  [ 25  91  88  -1  -1]
  [ 29  -1  49  20  29]
  [ -1  59   1  98  85]]

 [[ 86  -1  92  -1  74]
  [ 47  59  49  74  -1]
  [ -1  25  73  52  -1]
  [ 46  98   1  26  -1]]

 [[ 44  -1  -1  26  -1]
  [ -1 100  94  64  77]
  [ -1  -1  37 100  -1]
  [ -1  95  62  77  -1]]]
Second 2D array in the first dimension [[86 -1 92 -1 74]
 [47 59 49 74 -1]
 [-1 25 73 52 -1]
 [46 98  1 26 -1]]
First two rows, last three columns from each layer [[[-1 -1 20]
  [88 -1 -1]]

 [[92 -1 74]
  [49 74 -1]]

 [[-1 26 -1]
  [94 64 77]]]


Work with broadcasting and advanced operations in NumPy. Create a NumPy array arr of shape (3, 3) with random integers between
1 and 20. Perform the following:
•
Subtract the mean of each row from its respective elements (row-wise normalization).
•
Create a new array by squaring all the elements in arr.
•
Find the indices of the top 3 maximum values in the entire array.

In [28]:
arr = np.random.randint(1, 21, size=(3, 3))
row_means = np.mean(arr, axis=1, keepdims=True)
normalized_arr = arr - row_means
squared_arr = np.square(arr)
flat_arr = arr.flatten()
top_3_indices = np.argsort(flat_arr)[-3:]
print("Original Array:",arr)
print("Row-wise Normalized Array:",normalized_arr)
print("Squared Array:",squared_arr)
print("Indices of Top 3 Maximum Values (flattened array):",top_3_indices)
top_3_indices_2d = np.unravel_index(top_3_indices, arr.shape)
print("Row and Column Indices of Top 3 Maximum Values:",top_3_indices_2d)

Original Array: [[ 9 14  4]
 [11 17  9]
 [ 8 14 11]]
Row-wise Normalized Array: [[ 0.          5.         -5.        ]
 [-1.33333333  4.66666667 -3.33333333]
 [-3.          3.          0.        ]]
Squared Array: [[ 81 196  16]
 [121 289  81]
 [ 64 196 121]]
Indices of Top 3 Maximum Values (flattened array): [1 7 4]
Row and Column Indices of Top 3 Maximum Values: (array([0, 2, 1]), array([1, 1, 1]))
